def game():
    name=input('Geef jouw character een naam.')
    print ('Hallo, ' + name +'.')
    import time

    print("------------------------------------") 
    print("Dag 1") 
    print("------------------------------------") 

    print ("    ╔═══════════════════════════════════════════════════╗")
    print ("    ║        Het is de dag voor dat je weg gaat,        ║")
    print ("    ║         je zit in je huis het is  20:00           ║")
    print ("    ║        Morgen moet je s'ochtends vroeg uit bed.   ║")
    print ("    ╚═══════════════════════════════════════════════════╝")
    slapen = input ('Wil je nu gaan slapen? [j/n]')
    if slapen == 'j':
        print  ('Je hebt besloten om te gaan slapen.')
    elif slapen == 'n' :
        print  ('Je hebt besloten om langer wakker te blijven.')

    time.sleep(4)
    print("------------------------------------") 
    print("Dag 2") 
    print("------------------------------------") 
    print ("    ╔═══════════════════════════════════════════════════╗")
    print ("    ║  Je bent optijd wakker, je bereid je voor om      ║")
    print ("    ║           binnen de ruimtevaart te gaan.          ║")
    print ("    ║je krijgt momenteel instructies dat je moet volgen.║")
    print ("    ╚═══════════════════════════════════════════════════╝")
    time.sleep(6)
    print ("    ╔═══════════════════════════════════════════════════╗")
    print ("    ║  check de conditie van de ruimtevaart op dag 3.   ║")
    print ("    ║    verander de richting van de vaart op dag 5.    ║")
    print ("    ║  wanneer je op het planeet land stuur een signaal.║")
    print ("    ╚═══════════════════════════════════════════════════╝")
    time.sleep(12)
    print ("Het is tijd, je zit in de ruimtevaart.")
    print ("3...")
    time.sleep(1)
    print ("2..")
    time.sleep(1)
    print ("1.")
    time.sleep(1)

    print("""
              ___
        |     | |
       / \    | |
      |o-o|===|-|
      |-o-|   | |
     /     \  | |
    | U     | | |
    | S     |=| |
    | A     | | |
    |_______| |_|
     |@| |@|  | |
    __________|_|_
    """)
    time.sleep(5)

    print("------------------------------------") 
    print("Dag 3") 
    print("------------------------------------")
    time.sleep(3)
    print ("╔═════════════════════════════════════════════════════╗")
    print ("║          Het is 12 uur na de lancering...           ║")
    print ("║je hebt net iets gegeten en je hebt een taak gekregen║")
    print ("║             wat was het ook al weer?                ║")
    print ("╚═════════════════════════════════════════════════════╝")
    time.sleep(5)
    print ("╔═════════════════════════════════════════════════╗")
    print ("║  A: het schoonmaken van de ruimtevaard.         ║")
    print ("║  B: conditie checken van de ruimtevaard.        ║")
    print ("║  C: Verander de richting van de ruimtevaard.    ║")
    print ("╚═════════════════════════════════════════════════╝")
    vraag1=input ("je kunt kiezen tussen A,B en C")

    if vraag1 == ("A"):
        print ("╔══════════════════════════════════════════════════╗")
        print ("║ Je begint met het schoonmaken van de ruimtevaard.║")
        print ("╚══════════════════════════════════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 4") 
        print("------------------------------------")
        time.sleep(4)
        print ("╔═════════════════════════════════════════════════╗")
        print ("║Je wordt wakker door een raar geluid,je loop naar║")
        print ("║dat geluid toe... en daar zie je op het scherm.. ║")
        print ("║dat de ruimtevaard op elk moment kan neerstorten.║")
        print ("╚═════════════════════════════════════════════════╝")
        time.sleep(12)
        print ("Je bent dood")

    elif vraag1 == ("C"):
        print ("╔═════════════════════════════════════════════════╗")
        print ("║   Je Verander de richting van de ruimtevaard.   ║")
        print ("╚═════════════════════════════════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 4") 
        print("------------------------------------")
        print ("╔═════════════════════════════════════════════════╗")
        print ("║     Je wordt wakker je kijkt naar buiten...     ║")
        print ("║     je kan je ogen niet geloven...              ║")
        print ("║    je ziet een meteoriet naar je toe komen.     ║")
        print ("╚═════════════════════════════════════════════════╝")
        time.sleep(12)
        print ("Je bent dood")

    elif vraag1 == ("B"):
        print ("╔═════════════════════════════════════════════════╗")
        print ("║   Je checked de conditie van de ruimtevaard.    ║")
        print ("╚═════════════════════════════════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 4") 
        print("------------------------------------")
        time.sleep(5)
        print ("╔═════════════════════════════════════════════════╗")
        print ("║De conditie van de ruimtevaard is op goeie orde. ║")
        print ("╚═════════════════════════════════════════════════╝")
        time.sleep(5)
        print ("╔═════════════════════════════════════════════════╗")
        print ("║           Wat wil je nu gaan doen?              ║")
        print ("║   A: Verander de richting van de ruimtevaard.   ║")
        print ("║   B: het schoonmaken van de ruimtevaard. .      ║")
        print ("╚═════════════════════════════════════════════════╝")
        vraag2=input ("je kunt kiezen tussen A en B")
    if vraag2 == ("A"):
        print ("╔═════════════════════════════════════════════════╗")
        print ("║   Je Verander de richting van de ruimtevaard.   ║")
        print ("╚═════════════════════════════════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 5") 
        print("------------------------------------")
        print ("╔═════════════════════════════════════════════════╗")
        print ("║     Je wordt wakker je kijkt naar buiten...     ║")
        print ("║     je kan je ogen niet geloven...              ║")
        print ("║    je ziet een meteoriet naar je toe komen.     ║")
        print ("╚═════════════════════════════════════════════════╝")
        time.sleep(6)
        print ("Je bent dood")
    elif vraag2 == ("B"):
        print ("╔══════════════════════════════════════════════════╗")
        print ("║ Je begint met het schoonmaken van de ruimtevaard.║")
        print ("╚══════════════════════════════════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 5") 
        print("------------------------------------")
        time.sleep(4)
        print ("╔═════════════════════════════════════════════════╗")
        print ("║           Wat wil je nu gaan doen?              ║")
        print ("║   A: Verander de richting van de ruimtevaard.   ║")
        print ("║  B:Stuur een signaal terug naar de headquarters.║")
        print ("╚═════════════════════════════════════════════════╝")
        vraag3=input ("je kunt kiezen tussen A en B")
    if vraag3 == ("B"):
        print ("╔═════════════════════════════════╗")
        print ("║ Je stuurt een signaal terug...  ║")
        print ("╚═════════════════════════════════╝")
        time.sleep(5)
        print ("╔══════════════════════╗")
        print ("║    Geen reactie.     ║")
        print ("╚══════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 6") 
        print("------------------------------------")
        time.sleep(2)
        print ("╔═══════════════════════════════════════════╗")
        print ("║    Je had geen reactie terug gekregen.    ║")
        print ("║    de dag gaat voorbij zonder problemen.. ║")
        print ("╚═══════════════════════════════════════════╝")
        print("------------------------------------") 
        print("Dag 7") 
        print("------------------------------------")
        time.sleep(2)
        print ("╔═══════════════════════════════════════════╗")
        print ("║de dag gaat weer voorbij zonder problemen..║")
        print ("╚═══════════════════════════════════════════╝")
        print("------------------------------------") 
        print("Dag 8") 
        print("------------------------------------")
        time.sleep(5)
        print ("╔═══════════════════════════════════════════╗")
        print ("║                     ...                   ║")
        print ("╚═══════════════════════════════════════════╝")
        time.sleep(4)
        print ("...")

    elif vraag3 == ("A"):
        print ("╔═══════════════════════════════════════════╗")
        print ("║je Verander de richting van de ruimtevaard.║")
        print ("╚═══════════════════════════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 6") 
        print("------------------------------------")
        time.sleep(2)
        print ("╔═══════════════════════════════════════════╗")
        print ("║de dag gaat voorbij zonder problemen..     ║")
        print ("╚═══════════════════════════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 7") 
        print("------------------------------------")
        time.sleep(2)
        print ("╔════════════════════════════════════════════╗")
        print ("║  Het is je gelukt je bent op het planeet!  ║")
        print ("║         Wat wil je nu gaan doen?           ║")
        print ("╚════════════════════════════════════════════╝")
        time.sleep(4)
        print ("╔═══════════════════════════════════════════╗")
        print ("║  A: Een signaal sturen dat je er bent.    ║")
        print ("║        B: blijf in het ruimtevaard.       ║")
        print ("╚═══════════════════════════════════════════╝")
        vraag4=input ("je kunt kiezen tussen A en B")
    if vraag4 == ("B"):
        print ("╔═════════════════════════════════╗")
        print ("║ Je bleeft in het ruimtevaard.   ║")
        print ("╚═════════════════════════════════╝")
        time.sleep(3)
        print ("╔═══════════════════════════════════════════╗")
        print ("║   de dag gaat voorbij zonder problemen..  ║")
        print ("╚═══════════════════════════════════════════╝")
        time.sleep(5)
        print("------------------------------------") 
        print("Dag 7") 
        print("------------------------------------")
        time.sleep(4)
        print ("╔═══════════════════════════════════════════╗")
        print ("║    de dag gaat voorbij zonder problemen.. ║")
        print ("╚═══════════════════════════════════════════╝")
        time.sleep(3)
        print("------------------------------------") 
        print("Dag 8") 
        print("------------------------------------")
        time.sleep(3)
        print ("╔═══════════════════════════════════════════╗")
        print ("║de dag gaat weer voorbij zonder problemen..║")
        print ("╚═══════════════════════════════════════════╝")
        print("------------------------------------") 
        print("Dag 9") 
        print("------------------------------------")
        time.sleep(5)
        print ("╔═══════════════════════════════════════════╗")
        print ("║                     ...                   ║")
        print ("╚═══════════════════════════════════════════╝")
        time.sleep(4)
        print ("...")
    if vraag4 == ("A"):
        print ("╔═════════════════════════════════╗")
        print ("║ Je stuurt een signaal terug...  ║")
        print ("╚═════════════════════════════════╝")
        time.sleep(3)
        print ("╔════════════════════════════════╗")
        print ("║     Je krijgt een reactie!     ║")
        print ("║   Je hebt je taak voltooid,    ║")
        print ("║       Het is je gelukt.        ║")
        print ("╚════════════════════════════════╝")
        print ("Gewonnen.")

game()